# vim:fileencoding=utf-8:foldmethod=marker

# Fonts
font_family                             SF Mono 
font_size                               14.0
modify_font cell_height                 125%
modify_font underline_position          4
modify_font underline_thickness         150%

# Performance Tuning
repaint_delay 		                8
input_delay	                	3
sync_to_monitor		                yes

# Tab Bar
tab_bar_style                           powerline
tab_powerline_style                     angled

# Colorscheme
background_opacity                      1.0

# OS Specific Tweaks
macos_option_as_alt                     yes
macos_traditional_fullscreen            no
