gui:
  border: 'rounded'
  theme:
    selectedLineBgColor:
      - '#33415E'
    selectedRangeBgColor:
      - '#33415E'
git:
  branchLogCmd: "git lg"
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: 'nvim'
