-- LVim settings
reload("mira1zu.plugins")
reload("mira1zu.config")
reload("mira1zu.remap")

-- Languages
reload("mira1zu.lsp")
reload("mira1zu.null-ls")
reload("mira1zu.filetype")

-- Plugins settings
reload("mira1zu.alpha")
reload("mira1zu.auto-save")
reload("mira1zu.ayu")
reload("mira1zu.bufferline")
reload("mira1zu.cinnamon")
reload("mira1zu.copilot")
reload("mira1zu.flit")
reload("mira1zu.gitsigns")
reload("mira1zu.goto-preview")
reload("mira1zu.indent-blankline")
reload("mira1zu.leap")
reload("mira1zu.lsp-signature")
reload("mira1zu.lualine")
reload("mira1zu.markdown-preview")
reload("mira1zu.numb")
reload("mira1zu.nvim-cmp")
reload("mira1zu.nvim-lastplace")
reload("mira1zu.nvim-navic")
reload("mira1zu.nvim-tree")
reload("mira1zu.nvim-treesitter")
reload("mira1zu.obsidian")
reload("mira1zu.persistence")
reload("mira1zu.project")
reload("mira1zu.symbols-outline")
reload("mira1zu.telescope")
reload("mira1zu.toggleterm")
reload("mira1zu.trouble")
reload("mira1zu.virt-column")
reload("mira1zu.which-key")
reload("mira1zu.zen-mode")
